<?php
/**
 * @file
 * Main code for the Good Help Conf module.
 */

/**
 * Implements goodhelp_product_info().
 */
function goodhelp_conf_goodhelp_product_info() {
  return array(
    'noc' => array(
      'name' => 'NOC',
      'versions' => array(
        '4.6',
        '4.7',
        '4.7.1',
        '4.8',
        '4.9',
      ),
    ),
    'other_product' => array(
      'name' => 'Other Product',
      'versions' => array(
        '1',
        '2',
        '3',
        '4',
      ),
    ),
  );
}