<?php
/**
 * @file
 * Code for the goodhelp_conf feature.
 */

include_once 'goodhelp_conf.features.inc';

/**
 * Implements goodhelp_product_info().
 */
function goodhelp_conf_goodhelp_product_info() {
  return array(
    'noc' => array(
      'name' => 'NOC',
      'versions' => array(
        '4.7',
        '4.8',
        '4.9',
        '4.10',
      ),
    ),
  );
}

/**
 * Implements goodhelp_topic_id_options().
 */
function goodhelp_conf_goodhelp_topic_id_options() {
  return array(
    'noc_ann',
    'noc_audio',
    'noc_biography',
    'noc_blog',
    'noc_bookmark',
    'noc_calendar',
    'noc_chatterbox',
    'noc_dailyupdate',
    'noc_directory',
    'noc_file',
    'noc_forum',
    'noc_freehtml',
    'noc_image',
    'noc_link',
    'noc_memberinfo',
    'noc_org',
    'noc_page',
    'noc_people',
    'noc_poll',
    'noc_promo',
    'noc_qna',
    'noc_rss',
    'noc_section',
    'noc_story',
    'noc_task',
    'noc_uwall',
    'noc_video',
    'noc_wiki',
    'go_activitystream',
  );
}

/**
 * Implements hook_block_info().
 */
function goodhelp_conf_block_info() {
  $blocks = array();

  $blocks['goodhelp_conf_book_nav'] = array(
    'info' => 'HMS: Goodhelp Book Nav',
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function goodhelp_conf_block_view($delta) {
  $block = array();

  switch ($delta) {
    case 'goodhelp_conf_book_nav':
      $block['subject'] = t('Contents');
      $block['content'] = goodhelp_conf_book_nav_content();
      break;
  }

  return $block;
}

/**
 * Returns a book menu themed using jquerymenu, for use in the Book Nav block.
 */
function goodhelp_conf_book_nav_content() {
  // Get current book
  if ($node = menu_get_object()) {
    if (isset($node->book['bid'])) {
      $menu_name = $node->book['menu_name'];
      // Return themed menu.
      return theme('jquerymenu_menu', array('tree' => menu_tree_all_data($menu_name), 'trail' => menu_get_active_trail()));
    }
  }
  return '';
}

/**
 * Implements hook_views_pre_build().
 */
function goodhelp_conf_views_pre_build(&$view) {
  if ($view->name == 'topic_search') {
    // Set the override path to the current page. This will redirect the back view to
    // the current page when submitted in case AJAX fails.
    $view->override_path = $_GET['q'];
  }
}