<?php
/**
 * @file
 * Code for the goodhelp_conf feature.
 */

include_once 'goodhelp_conf.features.inc';

/**
 * Implements goodhelp_product_info().
 */
function goodhelp_conf_goodhelp_product_info() {
  return array(
    'noc' => array(
      'name' => 'NOC',
      'versions' => array(
        '4.7',
        '4.8',
        '4.9',
        '4.10',
      ),
    ),
  );
}

/**
 * Implements goodhelp_topic_id_options().
 */
function goodhelp_conf_goodhelp_topic_id_options() {
  return array(
    'noc_directory',
    'noc_blog',
    'noc_forum',
  );
}